# -*- coding: utf-8 -*-
text = """An automaton (100)
A working AI (15)
A working AI \(safely demonstrated) (20)
A terrifying technological terror (30)
A horrifying eldritch horror (30)
A set of interlocking cogs (10)
A set of interlocking cogs, functional if poked (15)
Previous Guest of Honour (30)
A Dave (25)
A sock with a hole in it (3)
Picocon (30)
The Picocon sofa (29)
Tea, Earl Grey, Hot (15)
Delicious blood (5)
The contents of my pocketses (7)
Good News (5)
Bad News (-5)
A funny joke (10)
A bad pun (-10)
A competent barbershop solo, because covid (25)
A competent barbershop quartet, social distanced (50)
Any song sung in the style of William Shatner (50)
A barbershop quartet in the style of William Shatner (100)
A door to the great beyond (15)
A teleological proof of the existence of a higher power (5)
A little fall of rain (7)
A demon bear (6.66)
Origami (20)
Dinosaur origami (27)
A non-euclidean triangle (8)
A snake eating its own tail, or snail (5)
An accretion disk (10)
A good hat (12)
A correctly fitted top hat (13)
“Convincing” cosplay (17)
Pretty trinkets (10)
A rotary dial phone (72)
Out of place k e rni ng (12)
An aesthetically pleasing key (17)
The World Turtle (23)
The Steampunk (19)
A book that should be returned to us after Covid, or now (50)
Famous last words (4)
A practical application of General Relativity (25)
A point in the complex plane: i * (1)
A swordfish (25)
A fishsword (35)
Nerf Guns (15)
Lab stuff (21)
Observable brownian motion (30)
A fluffy dragon (25)
A stable tower of 3 water bottles (8)
A wizards staff (10)
A cool bowtie (9)
A completed crossword (100)"""

import sqlite3

with sqlite3.connect('main.db') as db:
    for line in text.split("\n"):
        item, points = line.split(" (")
        points = float(points[:-1])
        print(item, points)
        db.execute("INSERT INTO treasure (name, value) VALUES (?, ?)", (item, points))
    db.commit()

with sqlite3.connect('main.db') as db:
    db.execute("UPDATE treasure SET id = id - 99")
    db.commit()

for i, line in enumerate(text.split("\n")):
    item, points = line.split(" (")
    points = float(points[:-1])
    print(i+1, item, points)


